name: Generate Token

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  generate-token:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate GitHub App Token
        id: generate-token
        run: |
          # Define variables
          APP_ID=${{ secrets.GH_APP__HELLO_WORLD_APP_ID }}
          PRIVATE_KEY="${{ secrets.GH_APP__HELLO_WORLD_PRIVATE_KEY }}"

          # Create JWT
          JWT=$(curl -X POST \
            -H "Authorization: Bearer $(echo -n "client_id=${APP_ID}&client_secret=${PRIVATE_KEY}" | base64)" \
            -H "Content-Type: application/x-www-form-urlencoded" \
            -d "grant_type=client_credentials" \
            https://github.com/login/oauth/access_token)

          # Extract token from the response
          ACCESS_TOKEN=$(echo $JWT | jq -r .access_token)

          # Output the token
          echo "ACCESS_TOKEN=${ACCESS_TOKEN}" >> $GITHUB_ENV

      - name: Use the Token
        run: |
          echo "Using the token..."
          # Example usage of the token
          curl -H "Authorization: Bearer ${{ env.ACCESS_TOKEN }}" \
            https://api.github.com/user/repos
