name: Maven Clean Build

on:
  push:
    branches: [ "*" ]
#  pull_request:
#    branches: [ "*" ]

jobs:
  build:
    name: Maven Clean Package
    runs-on: ubuntu-latest
    container: ershakiransari/jdk:8-mvn3

    steps:
      - uses: actions/checkout@v3

#      - name: Set up JDK 8
#        uses: actions/setup-java@v3
#        with:
#          java-version: '8'
#          distribution: 'corretto'
#          cache: maven

      - name: Build with Maven
        run: mvn clean package --no-transfer-progress
