name: Maven Central Deployment

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      version:
        description: Tag Version (add prefix v)
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v3

        # DO NOT USE CONTAINER, else gpg sign step will fail
      - name: Set up Java for publishing to Maven Central Repository
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: ossrh-ershakiransari
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Building artifact
        run: mvn clean package --no-transfer-progress

      - name: Publish to the Maven Central Repository
        run: |
          mvn deploy -P release -Dmaven.test.skip=true --no-transfer-progress -e
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}