name: Maven Central Deployment

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      version:
        description: Tag Version (add prefix v)
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    container: ershakiransari/jdk:8-mvn3
    steps:
      - name: Code checkout
        uses: actions/checkout@v3

      - name: Building artifact
        run: mvn clean package --no-transfer-progress

      - name: Publish to the Maven Central Repository
        run: |
          mvn deploy -P release -Dmaven.test.skip=true --no-transfer-progress -e
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}