name: Maven Clean Build

on:
  schedule:
    - cron: "*/30 * * * *" # every 30min UTC

jobs:
  build:
    name: Maven Clean Build
    runs-on: ubuntu-latest
    container: ershakiransari/jdk:8-mvn3

    steps:
      - name: Code checkout
        uses: actions/checkout@v4.1.1

      - name: Build with Maven
        run: mvn clean package --no-transfer-progress
